# Generated by Django 6.0.1 on 2026-02-25 16:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('reference', models.CharField(max_length=50, verbose_name='Reference')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('inspection_type', models.CharField(default='incoming', max_length=30, verbose_name='Inspection Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('inspector_id', models.UUIDField(blank=True, null=True, verbose_name='Inspector Id')),
                ('inspection_date', models.DateField(blank=True, null=True, verbose_name='Inspection Date')),
                ('result', models.CharField(default='pending', max_length=20, verbose_name='Result')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'db_table': 'quality_inspection',
                'abstract': False,
            },
        ),
    ]
